### ISSUE TITLE
Devices not in drop down list

### ISSUE THREAD

**Issue by butterchef** [hardillb/node-red-contrib-alexa-home-skill#19]
Hi
Sorry my english is not so good.
I have a problem with node-red-contrib-alexa-home-skill. In Node-RED Alexa Home Skill Bridge I have devices that Alexa also finds. In Node-Red I installed the node-red-contrib-alexa-home-skill V0.1.15. Node-Red has version v0.17.5. Node-red-contrib-alexa-home-skill connects to the bridge.
Now my problem is that node-red-contrib-alexa-home-skill no devices finds. The dropdown list is empty. Updating does not help either.
Also I tried with different browsers like Firefox, Microsoft edge, Microsoft Internet explorer, google chrome (from tablet). No devices are found in all browsers.

Can you help with this?

Many Thanks.

**Comment by hardillb** [comment]
Double check that your username and password are right in the config node.

Then check the Node-RED log and the Browser console for any errors at the point where you open the return from the config node to the node configuration dialog with the drop down.

Finally what is the username you have on the alexa-node-red site so I can check the logs

**Comment by butterchef** [comment]
A connection to the bridge is established. - see image.
![node-red](https://user-images.githubusercontent.com/30996413/29270667-2db724b2-80f8-11e7-9ea0-200d2c1ac1c6.jpg)
![node-red1](https://user-images.githubusercontent.com/30996413/29270668-2db808d2-80f8-11e7-9cb2-d73312be6841.jpg)
My user name is butteralexa
Where can I find the log files of node-red on the rasperry pi?

**Comment by butterchef** [comment]
Here is an image of the browser console
![internet-exploror-console](https://user-images.githubusercontent.com/30996413/29271315-1398d3f2-80fb-11e7-954f-4926d2c57acc.jpg)

**Comment by butterchef** [comment]
Here is an image of the chrome browser console...
![crome-console](https://user-images.githubusercontent.com/30996413/29273755-b90c26c2-8105-11e7-9ece-1248d889d671.jpg)

**Comment by hardillb** [comment]
The Node-RED logs depend on how you are running/installed it. Assuming you installed it using the update script then it will be running as a service and the logs end up in the system logs.

There is a command is `node-red-log` that will tail the log

**Comment by hardillb** [comment]
Also can you try restarting Node-RED. That error implies that the backend can't find the account credentials to look up the list of devices. Restarting Node-RED should fix this.

**Comment by jpenn84** [comment]
I'm running into the same issue. I deleted my credentials in the configuration nodes and created new ones. I still don't see the list.

```
node-red-logs: (I got 'can't refresh until deployed. Then I deployed and tried again)
Can't refresh until deployed
16 Aug 04:03:39 - [info] Stopping flows
pam_unix(sudo:session): session closed for user root
pam_unix(sudo:session): session closed for user root
pam_unix(sudo:session): session closed for user root
pam_unix(sudo:session): session closed for user root
pam_unix(sudo:session): session closed for user root
16 Aug 04:03:39 - [info] Stopped flows
16 Aug 04:03:39 - [info] Starting flows
16 Aug 04:03:39 - [error] [alexa-home:bd288c70.981f6] TypeError: Cannot read property 'register' of null
16 Aug 04:03:39 - [error] [alexa-home:982cadd8.823b7] TypeError: Cannot read property 'register' of null
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py out 29
pam_unix(sudo:session): session opened for user root by (uid=0)
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py out 31
pam_unix(sudo:session): session opened for user root by (uid=0)
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py out 32
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py out 35
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session opened for user root by (uid=0)
16 Aug 04:03:39 - [info] Started flows
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py out 40
pam_unix(sudo:session): session opened for user root by (uid=0)
Can't refresh until deployed
```

The Alexa node isn't listing any devices, but says I'm connected
<img width="746" alt="screen shot 2017-08-16 at 12 18 23 am" src="https://user-images.githubusercontent.com/7193403/29347180-aa52f55c-8218-11e7-8ef5-ad05f48c98ed.png">

And a screenshot of my devices listed on https://alexa-node-red.bm.hardill.me.uk/devices
<img width="465" alt="screen shot 2017-08-16 at 12 18 33 am" src="https://user-images.githubusercontent.com/7193403/29347184-b1431bb2-8218-11e7-8990-2a75a9bdd697.png">

**Comment by butterchef** [comment]
I have tested it with two devices (RaspberryPi 3b and IOT2000 from Siemens). For both devices is the same problem.
Must be open for access to https://alexa-node-red.bm.hardill.me.uk/ determined ports?

**Comment by hardillb** [comment]
The whole system is down at the moment because the the cert has expired. I
will fix that later today then look ups should work again

**Comment by hardillb** [comment]
The certificate has been updated. Please test again.

**Comment by butterchef** [comment]
Perfect, now works.
Many Thanks
